project:
  type: website
  output-dir: docs

website:
  title: "Ashok P"
  description: "Few thoughts on Transport Planning and Programming"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ashokpamidi/
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: Sandstone
    css: styles.css

editor: visual

